// global
export const CALLING_SERVER = 'CALLING_SERVER'
export const SERVER_RETURNED = 'SERVER_RETURNED'
export const DIALOG_OK = 'DIALOG_OK'
export const DIALOG_OK_CANCEL = 'DIALOG_OK_CANCEL'
export const DIALOG_YES_NO = 'DIALOG_YES_NO'
export const CLEAR_DIALOG = 'CLEAR_DIALOG'
export const ERROR = 'ERROR'
export const USER_WARNING = 'USER_WARNING'

export const MENU_SELECTED = 'MENU_SELECTED'

// session
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

// projects
export const PROJECTS_LOADED = 'PROJECTS_LOADED'
// export const VIEW_PROJECTS = 'VIEW_PROJECTS'
// export const NEW_PROJECT = 'NEW_PROJECT'
// export const CANCEL_NEW_PROJECT = 'CANCEL_NEW_PROJECT'
// export const SAVING_PROJECT = 'SAVING_PROJECT'
export const PROJECT_SAVED = 'PROJECT_SAVED'
// export const DELETING_PROJECT = 'DELETING_PROJECT'
export const PROJECT_DELETED = 'PROJECT_DELETED'
// export const VIEW_PROJECT_DETAIL = 'VIEW_PROJECT_DETAIL'

// budget
export const BUDGETS_LOADED = 'BUDGETS_LOADED'
export const VIEW_BUDGET = 'BUDGET_VIEW_DETAIL'
export const EDIT_BUDGET = 'BUDGET_EDIT'
export const ADD_BUDGET_ROLE = 'ADD_BUDGET_ROLE'
export const SAVE_ACTIVE_BUDGET = 'SAVE_ACTIVE_BUDGET'
export const BACK_TO_BUDGET_SUMMARY = 'BACK_TO_BUDGET_SUMMARY'
export const FTE_UPDATED = 'FTE_UPDATED'
export const BUDGET_SAVED = 'BUDGET_SAVED'
// export const CANCEL_BUDGET_UPDATE = 'CANCEL_BUDGET_UPDATE'
// export const NEW_BUDGET = 'NEW_BUDGET'
export const DELETE_BUDGET = 'BUDGET_DELETE'
export const BUDGET_DELETED = 'BUDGET_DELETED'
export const UPDATE_BUDGET_NAME = 'UPDATE_BUDGET_NAME'
// export const BUDGET_UPDATED = 'BUDGET_UPDATED'
export const BUDGET_DEFAULT_SET = 'BUDGET_DEFAULT_SET'
export const VIEW_RESOURCE_SUMMARY = 'VIEW_RESOURCE_SUMMARY'
