const ActionTypes = {

// global
  CALLING_SERVER: 'CALLING_SERVER',
  SERVER_RETURNED: 'SERVER_RETURNED',
  DIALOG_OK: 'DIALOG_OK',
  DIALOG_OK_CANCEL: 'DIALOG_OK_CANCEL',
  DIALOG_YES_NO: 'DIALOG_YES_NO',
  CLEAR_DIALOG: 'CLEAR_DIALOG',
  ERROR: 'ERROR',
  USER_WARNING: 'USER_WARNING',

  MENU_SELECTED: 'MENU_SELECTED',

// session
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',

// projects
  PROJECTS_LOADED: 'PROJECTS_LOADED',
  PROJECT_SAVED: 'PROJECT_SAVED',
  PROJECT_DELETED: 'PROJECT_DELETED',

// budget
  NEW_BUDGET: 'BUDGET_NEW',
  BUDGETS_LOADED: 'BUDGETS_LOADED',
  VIEW_BUDGET: 'BUDGET_VIEW_DETAIL',
  EDIT_BUDGET: 'BUDGET_EDIT',
  ADD_BUDGET_ROLE: 'BUDGET_ADD_ROLE',
  SAVE_ACTIVE_BUDGET: 'SAVE_ACTIVE_BUDGET',
  BACK_TO_BUDGET_SUMMARY: 'BACK_TO_BUDGET_SUMMARY',
  FTE_UPDATED: 'FTE_UPDATED',
  BUDGET_SAVED: 'BUDGET_SAVED',
  DELETE_BUDGET: 'BUDGET_DELETE',
  BUDGET_DELETED: 'BUDGET_DELETED',
  BUDGET_UPDATED: 'BUDGET_UPDATED',
  UPDATE_BUDGET_NAME: 'UPDATE_BUDGET_NAME',
  VIEW_RESOURCE_SUMMARY: 'VIEW_RESOURCE_SUMMARY',

}

export default ActionTypes
